# (nombre en salida CSV, título exacto del artículo en es.wikipedia.org)
ESTADOS_WIKI: list[tuple[str, str]] = [
    ("Aguascalientes", "Anexo:Gobernantes de Aguascalientes"),
    ("Baja California", "Anexo:Gobernantes de Baja California"),
    ("Baja California Sur", "Anexo:Gobernantes de Baja California Sur"),
    ("Campeche", "Anexo:Gobernantes de Campeche"),
    ("Chiapas", "Anexo:Gobernantes de Chiapas"),
    ("Chihuahua", "Anexo:Gobernantes de Chihuahua"),
    ("Coahuila", "Anexo:Gobernantes de Coahuila"),
    ("Colima", "Anexo:Gobernantes de Colima"),
    ("Ciudad de México", "Anexo:Gobernantes de Ciudad de México"),
    ("Durango", "Anexo:Gobernantes de Durango"),
    ("Guanajuato", "Anexo:Gobernantes de Guanajuato"),
    ("Guerrero", "Anexo:Gobernantes de Guerrero"),
    ("Hidalgo", "Anexo:Gobernantes de Hidalgo"),
    ("Jalisco", "Anexo:Gobernantes de Jalisco"),
    ("Estado de México", "Anexo:Gobernantes del Estado de México"),
    ("Michoacán", "Anexo:Gobernantes de Michoacán"),
    ("Morelos", "Anexo:Gobernantes de Morelos"),
    ("Nayarit", "Anexo:Gobernantes de Nayarit"),
    ("Nuevo León", "Anexo:Gobernantes de Nuevo León"),
    ("Oaxaca", "Anexo:Gobernantes de Oaxaca"),
    ("Puebla", "Anexo:Gobernantes de Puebla"),
    ("Querétaro", "Anexo:Gobernantes de Querétaro"),
    ("Quintana Roo", "Anexo:Gobernantes de Quintana Roo"),
    ("San Luis Potosí", "Anexo:Gobernantes de San Luis Potosí"),
    ("Sinaloa", "Anexo:Gobernantes de Sinaloa"),
    ("Sonora", "Anexo:Gobernantes de Sonora"),
    ("Tabasco", "Anexo:Gobernantes de Tabasco"),
    ("Tamaulipas", "Anexo:Gobernantes de Tamaulipas"),
    ("Tlaxcala", "Anexo:Gobernantes de Tlaxcala"),
    ("Veracruz", "Anexo:Gobernantes de Veracruz"),
    ("Yucatán", "Anexo:Gobernantes de Yucatán"),
    ("Zacatecas", "Anexo:Gobernantes de Zacatecas"),
]
